### ISSUE TITLE
Feature Request: expose separate API interfaces for each cipher

### ISSUE THREAD

**Issue by bdbai** [shadowsocks/shadowsocks-crypto#13]
Currently, we have a unified cipher interface ([`Cipher`](https://docs.rs/shadowsocks-crypto/latest/shadowsocks_crypto/v1/enum.Cipher.html#)) that encapsulates all cryptography operations on each supported cipher. While the existing API interface is simple enough to use, the users have little control over details. For those applications that only use certain selected ciphers, the cost of cipher matching can be considered as overhead. Therefore, I would like to know if exposing cipher details as public interfaces is acceptable, and hopefully help to work on it.

**Comment by zonyitoo** [comment]
Why not use the underlying crypto interfaces directly?

**Comment by bdbai** [comment]
@zonyitoo Correct me if I am wrong, AFAIK the underlying crypto interfaces are not publicly visible.

**Comment by zonyitoo** [comment]
I mean you can use thouse libraries directly.

**Comment by bdbai** [comment]
Shadowsocks-specific ciphers and encryption schemes implemented in this repo may be useful in various scenarios. All we need is presumably just adding a couple of `pub` keywords.

@zonyitoo Before making final decisions, may I know the reason not to make underlying cipher implementations public?

**Comment by zonyitoo** [comment]
Making these ciphers public means that we have to maintain the stable public APIs for those underlying ciphers, which will make it harder to switch the underlying ciphers' implementations.

**Comment by bdbai** [comment]
> Making these ciphers public means that we have to maintain the stable public APIs for those underlying ciphers, which will make it harder to switch the underlying ciphers' implementations.

Makes sense! So I will just close this issue in light of the consideration above.
