### ISSUE TITLE
`neon` feature is not yet available on crates.io

### ISSUE THREAD

**Issue by sorairolake** [shadowsocks/shadowsocks-crypto#19]
This was added on December 2022 (at RustCrypto/stream-ciphers#310), but the latest version of `chacha20` crate was released on February 2022.

**Comment by zonyitoo** [comment]
Yes, it's true. Should we temporary remove `neon` feature of `chacha20`?

**Comment by sorairolake** [comment]
@zonyitoo I think it's good to do so, because this cannot build as it's now.
